"""Initial schema: weekly_demand and sku_metadata tables

Revision ID: 4074500e0b30
Revises: 
Create Date: 2026-03-04 19:15:04.346268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4074500e0b30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sku_metadata',
    sa.Column('sku_id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_table('weekly_demand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.String(length=20), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'week_start', name='uq_sku_week')
    )
    op.create_index('ix_sku_id', 'weekly_demand', ['sku_id'], unique=False)
    op.create_index('ix_week_start', 'weekly_demand', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_week_start', table_name='weekly_demand')
    op.drop_index('ix_sku_id', table_name='weekly_demand')
    op.drop_table('weekly_demand')
    op.drop_table('sku_metadata')
    # ### end Alembic commands ###
